### ISSUE TITLE
What's wrong with my CSV file

### ISSUE THREAD

**Issue by SergeWSU** [mpi-astronomy/gdr3apcal#12]
Hi
Thanks for the help with configuration file issue - now solved

I am however encountering an issue with my CSV file

teff_gspphot,logg_gspphot,mh_gspphot,azero_gspphot,ebpminrp_gspphot,ag_gspphot,mg_gspphot,(ra, dec),libname_gspphot
5957,4.16,-0.1438,0.0042,0.0019,0.0035,3.5485,"327.65,-27.81",MARCS

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\models\mars_mh.py: 682ec200c6392244c50e5659a9ff9923f6dd1f801e33fabb40a9fa93ba58c031
Model mh (C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gdr3apcal\models\mars_mh.py) **input file does not match the configuration**.**Expecting bd102a2b38e161e6c770650e021d2d8696542e2bddd411d0a590fe28f24030fa, got 682ec200c6392244c50e5659a9ff9923f6dd1f801e33fabb40a9fa93ba58c031

Thanks in advance

S

**Comment by mfouesneau** [comment]
How does pandas read your file? I feel the (ra,dec) column is problematic.

The messages you paste are warnings, not the error message.

**Comment by SergeWSU** [comment]
OK - Looks like RA and Dec need to be in separate columns. The quick start was a little unclear.
I can get metal_calib to run which is my main goal so thanks to all.

teff_calib is not working get the following error
teff_calib = calib.calibrateTeff(df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'GaiaDR3_GSPPhot_cal' object has no attribute 'calibrateTeff'

As noted above I can get metal_calib to run and am thankful for all the help.

I am closing the thread.

**Comment by mfouesneau** [comment]
Teff calib has been deprecated and removed. This is not a code bug.
