### ISSUE TITLE
calibrateTeff not yet implemented?

### ISSUE THREAD

**Issue by Rumpelstil** [mpi-astronomy/gdr3apcal#3]
Running the example results in 
AttributeError: 'GaiaDR3_GSPPhot_cal' object has no attribute 'calibrateTeff'

Do I understand it correctly that calibrateTeff was not yet been implemented? It is featured in the example, yet the readme states that only [M/H] is provided. Any ETA guess on when this might become available?

**Comment by mfouesneau** [comment]
Actually the teff model is not accurate and has been removed. If you find a need, let us know and we can include it here.
